version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
      day: '1'
      time: '09:00'
      timezone: 'UTC'
    open-pull-requests-limit: 2
    groups:
      js-all-updates:
        patterns:
          - '*'
    labels:
      - 'dependencies'
      - 'automated'
    commit-message:
      prefix: 'deps'
      include: 'scope'
