version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    reviewers:
      - 'Kravalg'
    groups:
      all-deps:
        patterns:
          - '*'
        update-types:
          - 'minor'
          - 'patch'
    commit-message:
      prefix: 'feat'
      prefix-development: 'chore'
      include: 'scope'
      