version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
      time: '09:00'
      timezone: 'UTC'
    open-pull-requests-limit: 2
    groups:
      js-all-updates:
        patterns:
          - '*'
    labels:
      - 'dependencies'
      - 'automated'
    commit-message:
      prefix: 'deps'
      include: 'scope'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      time: '09:00'
      timezone: 'UTC'
    open-pull-requests-limit: 5
    groups:
      github-actions-all:
        patterns:
          - '*'
    labels:
      - 'dependencies'
      - 'automated'
    commit-message:
      prefix: 'deps'
      include: 'scope'

  - package-ecosystem: 'docker'
    directories:
      - '/'
      - '/src/test/load'
    schedule:
      interval: 'weekly'
      time: '09:00'
      timezone: 'UTC'
    open-pull-requests-limit: 5
    groups:
      docker-all:
        patterns:
          - '*'
    labels:
      - 'dependencies'
      - 'automated'
    commit-message:
      prefix: 'deps'
      include: 'scope'
