services:
  memory-leak:
    build:
      context: .
      dockerfile: MemoryLeak.Dockerfile
    volumes:
      - .:/app
      - memleak_node_modules:/app/node_modules
    ports:
      - '5050:5050'
    environment:
      - DISPLAY=:99
      - PUPPETEER_DISABLE_HEADLESS_WARNING=1
      - NEXT_PUBLIC_PROD_CONTAINER_API_URL=http://prod:3001
      - DEBUG=puppeteer:*
      - MEMLAB_DEBUG=1
    init: true
    shm_size: '1gb'
    healthcheck:
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
      test: ["CMD", "chromium-browser", "--version"]

volumes:
  memleak_node_modules:
