services:
  prod:
    build: .
    command: pnpm run start
    restart: unless-stopped
    volumes:
      - .:/app
    ports:
      - '3001:3001'

  playwright:
    build:
      context: .
      dockerfile: Playwright.Dockerfile
    restart: unless-stopped
    volumes:
      - .:/app
    ports:
      - '9323:9323'
