services:
  memory-leak:
    build:
      context: .
      dockerfile: MemoryLeak.Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    init: true
    shm_size: '1gb'
    healthcheck:
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
      test: ["CMD", "chromium-browser", "--version"]
