services:
  prod:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "next build && next-export-optimize-images && npx serve -s out -p 3001"
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '3001:3001'

  playwright:
    build:
      context: .
      dockerfile: Playwright.Dockerfile
    restart: unless-stopped
    volumes:
      - .:/app
    ports:
      - '9324:9324'
    environment:
      - NEXT_PUBLIC_PRODUCTION_API_URL=http://prod:3001

  apollo:
    build:
      context: .
      dockerfile: Apollo.Dockerfile
    restart: unless-stopped
    ports:
      - '4000:4000'

  mockoon:
    build:
      context: .
      dockerfile: Mockoon.Dockerfile
    ports:
      - '8080:8080'
    restart: unless-stopped
