services:
  prod:
    build:
      context: .
      dockerfile: Dockerfile
    command: pnpm run start-prod
    restart: unless-stopped
    volumes:
      - .:/app
    ports:
      - '3001:3001'

  playwright:
    build:
      context: .
      dockerfile: Playwright.Dockerfile
    restart: unless-stopped
    volumes:
      - .:/app
    ports:
      - '9323:9323'

  apollo:
    build:
      context: .
      dockerfile: Apollo.Dockerfile
    volumes:
      - .:/app
    ports:
      - '4000:4000'
