x-healthcheck-default: &default-healthcheck
  interval: 30s
  timeout: 10s
  retries: 5

services:
  prod:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "npx next build && npx next-export-optimize-images && npx serve -s out -p 3001"
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '3001:3001'
    healthcheck:
        <<: *default-healthcheck
        test: [ "CMD", "curl", "-f", "http://localhost:3001" ]

  playwright:
    build:
      context: .
      dockerfile: Playwright.Dockerfile
    restart: unless-stopped
    volumes:
      - .:/app
    ports:
      - '9324:9324'
    environment:
      - NEXT_PUBLIC_PRODUCTION_API_URL=http://prod:3001
    healthcheck:
        <<: *default-healthcheck
        test: [ "CMD", "curl", "-f", "http://localhost:9324" ]


  apollo:
    build:
      context: .
      dockerfile: Apollo.Dockerfile
    restart: unless-stopped
    ports:
      - '4000:4000'
    healthcheck:
        <<: *default-healthcheck
        test: [ "CMD", "curl", "-f", "http://localhost:4000/graphql" ]

  mockoon:
    build:
      context: .
      dockerfile: Mockoon.Dockerfile
    ports:
      - '8080:8080'
    restart: unless-stopped
    healthcheck:
      <<: *default-healthcheck
      test: [ "CMD", "curl", "-f", "http://localhost:8080" ]
