x-healthcheck-default: &default-healthcheck
  interval: 30s
  timeout: 10s
  retries: 5
  start_period: 60s


x-healthchecks:
  healthcheck-prod: &healthcheck-prod
    <<: *default-healthcheck
    test: ["CMD", "curl", "-f", "http://localhost:3001"]

  healthcheck-playwright: &healthcheck-playwright
    <<: *default-healthcheck
    test: [ "CMD", "curl", "-f", "http://localhost:3001" ]

  healthcheck-apollo: &healthcheck-apollo
    <<: *default-healthcheck
    test: ["CMD", "curl", "-f", "http://localhost:4000/graphql"]

  healthcheck-mockoon: &healthcheck-mockoon
    healthcheck:
      <<: *default-healthcheck
      test: ["CMD", "curl", "-f", "http://localhost:8080"]

  healthcheck-dev: &healthcheck-dev
    healthcheck:
      <<: *default-healthcheck
      test: [ "CMD", "curl", "-f", "http://localhost:3000" ]
