services:
  memory-leak:
    container_name: website-memory-leak
    build:
      context: .
      dockerfile: MemoryLeak.Dockerfile
      target: final
    environment:
      - DISPLAY=:99
      - PUPPETEER_DISABLE_HEADLESS_WARNING=1
      - NEXT_PUBLIC_PROD_CONTAINER_API_URL=http://website-prod:3001
      - MEMLAB_DEBUG=true
      - MEMLAB_SKIP_WARMUP=true
      - NEXT_PUBLIC_CONTINUOUS_DEPLOYMENT_HEADER_NAME=no-aws-header-name
      - NEXT_PUBLIC_CONTINUOUS_DEPLOYMENT_HEADER_VALUE=no-aws-header-value
    init: true
    shm_size: '1gb'
    ipc: host
    tmpfs:
      - /dev/shm:size=1g
    networks:
      - website-network
    healthcheck:
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
      test: ["CMD", "chromium-browser", "--version"]

networks:
  website-network:
    external: true
    name: website-network
