services:
  prod:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh /app/scripts/start-prod.sh
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '3001:3001'
    extends:
      file: common-healthchecks.yml
      service: base-service
    healthcheck:
      test: ["CMD", "curl", "-f", "http://${LOCAL_HOST}:${NEXT_PUBLIC_PROD_PORT}"]

  playwright:
    build:
      context: .
      dockerfile: Playwright.Dockerfile
    restart: unless-stopped
    volumes:
      - .:/app
    ports:
      - '9324:9324'
    environment:
      - NEXT_PUBLIC_PROD_HOST_API_URL=http://prod:3001
    extends:
      file: common-healthchecks.yml
      service: base-service
    healthcheck:
      test: ["CMD", "curl", "-f", "http://${LOCAL_HOST}:${PLAYWRIGHT_TEST_PORT}"]


  apollo:
    build:
      context: .
      dockerfile: Apollo.Dockerfile
    restart: unless-stopped
    ports:
      - '4000:4000'
    extends:
      file: common-healthchecks.yml
      service: base-service
    healthcheck:
      test: ["CMD", "curl", "-f", "http://${LOCAL_HOST}:${GRAPHQL_PORT}/${GRAPHQL_API_PATH}"]

  mockoon:
    build:
      context: .
      dockerfile: Mockoon.Dockerfile
    ports:
      - '8080:8080'
    restart: unless-stopped
    extends:
      file: common-healthchecks.yml
      service: base-service
    healthcheck:
      test: ["CMD", "curl", "-f", "http://${LOCAL_HOST}:${MOCKOON_PORT}"]


  k6:
    profiles: ["load"]
    build:
      context: .
      dockerfile: ./src/test/load/Dockerfile
    depends_on:
      prod:
        condition: service_healthy
    volumes:
      - ./src/test/load:/loadTests
