name: codecov

on:
  pull_request:
    branches:
      - main

jobs:
  codecov:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.NODE_VERSION }}

      - name: Cache pnpm dependencies
        id: cache-pnpm-dependencies
        uses: actions/cache@v4.2.3
        with:
          path: node_modules
          key: ${{ runner.os }}-dependencies-node-${{ vars.NODE_VERSION }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-dependencies-node-${{ vars.NODE_VERSION }}-

      - name: Enable repo pnpm version
        run: |
          corepack enable
          corepack prepare $(node -p "require('./package.json').packageManager") --activate

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run unit tests
        run: make test-unit-all

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
