name: e2e testing

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ vars.NODE_VERSION }}

      - name: Install Dependencies
        run: npm ci

      - name: Run E2E tests with Playwright
        uses: bahmutov/start-server-and-test@v1.0.0
        with:
          start: npm start
          test: npm test
          url: http://localhost:3000
        env:
          PORT: 3001

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
