name: load testing

on:
  pull_request:
    branches:
      - main

jobs:
  load-testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ vars.NODE_VERSION }}

      - name: Run homepage load tests
        run: make load-tests

      - name: Run Swagger load tests
        run: make load-tests-swagger
