name: load testing

on:
  pull_request:
    branches:
      - main

jobs:
  load-testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ vars.NODE_VERSION }}

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: make install

      - name: Start application
        run: make start-prod

      - name: Wait for services
        run: make wait-for-prod

      - name: Run load tests
        run: make load-tests
