name: memory leak testing

on:
  pull_request:
    branches:
      - main
jobs:
  memory-leak-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ vars.NODE_VERSION }}

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: make install

      - name: Run dev and memory leak testing
        run: make test-memory-leak

        env:
          CI: true
