name: memory leak testing

on:
  pull_request:
    branches:
      - main

jobs:
  memory-leak-testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ vars.NODE_VERSION }}

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install memlab
        run: npm install -g memlab

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Run dev and memory leak testing
        run: |
          pnpm run dev:en &
          npx wait-on http://localhost:3000
          node ./src/test/memory-leak/runMemlabTests.js
        env:
          CI: true
