name: SandBox Rebuild

on: push

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout
jobs:
  AssumeRoleAndStartExecution:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_CODEPIPELINE_ROLE_ARN }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}
    
      - name: Validate Required Secrets
        run: |
          missing_secrets=()
          [ -z "${{ secrets.AWS_SANDBOX_CODEPIPELINE_NAME }}" ] && missing_secrets+=("AWS_SANDBOX_CODEPIPELINE_NAME")
          [ -z "${{ secrets.AWS_CODEPIPELINE_ROLE_ARN }}" ] && missing_secrets+=("AWS_CODEPIPELINE_ROLE_ARN")
          if [ ${#missing_secrets[@]} -ne 0 ]; then
            echo "::error::Missing required secrets: ${missing_secrets[*]}"
            exit 1
          fi

      - name: Start Pipeline Execution
        run: |
          if ! aws codepipeline start-pipeline-execution \
            --name "${{ secrets.AWS_SANDBOX_CODEPIPELINE_NAME }}" \
            --variables \
              "name=BRANCH_NAME,value=${BRANCH_NAME}" \
              "name=IS_PULL_REQUEST,value=0"; then
            echo "::error::Failed to start pipeline execution"
            exit 1
          fi
