name: Trigger Sandbox Deletion

on:
  pull_request:
    types:
      - closed
    branches:
      - main  

env:
  AWS_REGION: ${{ vars.AWS_REGION }}

jobs:
  trigger-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Trigger AWS CodePipeline
        uses: aws-actions/aws-codepipeline-action@v1
        with:
          pipeline-name: sandbox-deletion
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: ${{ env.AWS_REGION }}