name: security testing

on:
  pull_request:
    branches:
      - main

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        language: [typescript]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache CodeQL databases
        uses: actions/cache@v4.2.3
        with:
          path: ${{ github.workspace }}/codeql_databases
          key: ${{ runner.os }}-codeql-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-codeql-

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}

      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
