name: Visual Tests

on:
  pull_request:
    branches:
      - main

jobs:
  visual-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ vars.NODE_VERSION }}

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: make install

      - name: Verify required files
        run: |
          if [ ! -f "playwright.config.ts" ]; then
            echo "Error: playwright.config.ts is missing"
            exit 1
          fi
          if [ ! -f "Playwright.Dockerfile" ]; then
            echo "Error: Playwright.Dockerfile is missing"
            exit 1
          fi

      - name: Start application
        run: make start-prod

      - name: Wait for services
        run: make wait-for-prod

      - name: Run visual tests
        run: make test-visual

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
