name: Visual Tests

on:
  pull_request:
    branches:
      - main

jobs:
  visual-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ vars.NODE_VERSION }}

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: make install

      - name: Start application
        run: |
          make start & 
          sleep 10

      - name: Wait for server to be ready
        run: |
          echo "Waiting for the server to be available..."
          n=0
          until nc -z localhost 3000; do
            if [ $n -ge 10 ]; then
              echo "Server did not start in time"
              exit 1
            fi
            n=$((n+1))
            sleep 5
          done
          echo "Server is ready on port 3000"
        

      - name: Run visual tests
        run: make test-visual

